---
- hosts: 172.31.92.86
  become: yes
  tasks:
  - include_tasks: createfolder.yml
  - include_tasks: myfile.yml
  - name: i want to install apache2
    apt:
      name: apache2
      state: present
  
  - name: copy file on node side
    copy:
      src: mytextfile
      dest: /home/laksh/filehandling/mytextfile
  
  - name: download internet file
    get_url:
      url: https://updates.jenkins.io/download/war/2.507/jenkins.war
      dest: /home/laksh/filehandling/jenkins.war
      force_basic_auth: yes

  - name: Copy index file into node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: startwebserver 
  
  handlers:
    - name: startwebserver
      service:
        name: apache2
        state: restarted