---
- hosts: allnodeservers
  become: yes
  tasks:
  - name: install apache2 server (apt_get install apache2)
    apt:
      name: {{myunbuntuwebpackage}}
      state: present # if not mentioned then default is present
    when: ansible_os_family=="Debian"
  
  - name: I want to start apache2 webserver (service apache2 start)
    service:
      name: {{myunbuntuwebpackage}}
      state: started
    when: ansible_os_family=="Debian"

  - name: i want to install httpd webserver (yum install httpd)
    dnf:
      name: {{myredhatwebpackage}}
      state: present
    when: ansible_os_family=="RedHat"

  - name: i want to start httpd webserver (service httpd start)
    service:
      name: {{myredhatwebpackage}}
      state: started
    when: ansible_os_family=="RedHat"
   

# apt-get install apache2 for debian
# yum install httpd for amazonlinux "RedHat"