---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 server (apt_get install apache2)
    apt:
      name: apache2
      state: present # if not mentioned then default is present
  
  - name: I want to start apache2 webserver (service apache2 start)
    service:
      name: apache2
      state: started