---
- name: download tomcat tar file
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.40/bin/apache-tomcat-10.1.40.tar.gz
    dest: /home/laksh/apache-tomcat-10.1.40.tar.gz
    force_basic_auth: yes

- name: create tomcat folder (sudo mkdir -p /opt/tomcat)
  file:
    path: /opt/tomcat
    state: directory

- name: extract tomcat tar file (sudo tar xzvf apache-tomcat-10*tar.gz -C /opt/tomcat --strip-components=1)
  command:
    cmd: sudo tar xzvf /home/laksh/apache-tomcat-10.1.40.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE # if LICENSE file is not existed then extract

